Cisreg course
=============

Course on the analysis of cis-regulatory elements from genomic sequences

[View the Project on GitHub
jvanheld/cisreg\_course](https://github.com/jvanheld/cisreg_course)

-   [Download **ZIP
    File**](https://github.com/jvanheld/cisreg_course/zipball/master)
-   [Download **TAR
    Ball**](https://github.com/jvanheld/cisreg_course/tarball/master)
-   [View On **GitHub**](https://github.com/jvanheld/cisreg_course)

### [](#Contributors)Contributors

- Bruno Contreras Moreira
- Jaime Castro Mondragon
- Denis Puthier
- [Jacques van Helden](http://jacques.van-helden.perso.luminy.univ-amu.fr/)

### [](#designer-templates)Designer Templates

We’ve crafted some handsome templates for you to use. Go ahead and click
'Continue to layouts' to browse through them. You can easily go back to
edit your page before publishing. After publishing your page, you can
revisit the page generator and switch to another theme. Your Page
content will be preserved.

### [](#creating-pages-manually)Creating pages manually

If you prefer to not use the automatic generator, push a branch named
`gh-pages` to your repository to create a page manually. In addition to
supporting regular HTML content, GitHub Pages support Jekyll, a simple,
blog aware static site generator. Jekyll makes it easy to create
site-wide headers and footers without having to copy them across every
page. It also offers intelligent blog support and other advanced
templating features.

### [](#authors-and-contributors)Authors and Contributors

You can [@mention](https://github.com/blog/821) a GitHub username to
generate a link to their profile. The resulting `<a>` element will link
to the contributor’s GitHub Profile. For example: In 2007, Chris
Wanstrath ([@defunkt](https://github.com/defunkt)), PJ Hyett
([@pjhyett](https://github.com/pjhyett)), and Tom Preston-Werner
([@mojombo](https://github.com/mojombo)) founded GitHub.

### [](#support-or-contact)Support or Contact

Having trouble with Pages? Check out our
[documentation](https://help.github.com/pages) or [contact
support](https://github.com/contact) and we’ll help you sort it out.

This project is maintained by [jvanheld](https://github.com/jvanheld)

Hosted on GitHub Pages — Theme by
[orderedlist](https://github.com/orderedlist)
